ALTER TABLE student ALTER COLUMN birthday DATE NOT NULL;

ALTER TABLE mark ALTER COLUMN mark INT CHECK (mark >= 1 AND mark <= 10) NOT NULL;
ALTER TABLE mark ALTER COLUMN student_id BIGINT NOT NULL;
ALTER TABLE mark ALTER COLUMN subject_id BIGINT NOT NULL;

ALTER TABLE subject ALTER COLUMN grade INT CHECK (grade >= 1 AND grade <= 5);

ALTER TABLE PaymentType ALTER COLUMN name VARCHAR(255) UNIQUE ;

ALTER TABLE Payment ALTER COLUMN type_id BIGINT NOT NULL;
ALTER TABLE Payment ALTER COLUMN amount decimal NOT NULL ;
ALTER TABLE Payment ALTER COLUMN date DateTime NOT NULL ;