CREATE TABLE student (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, name varchar(255), birthday DATE, group INT);
CREATE TABLE subject (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, name varchar(255), description varchar(255), grade INT);
CREATE TABLE paymenttype (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, name varchar(255));
CREATE TABLE payment (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, type_id BIGINT FOREIGN KEY REFERENCES peymenttype(id), amount decimal, student_id BIGINT FOREIGN KEY REFERENCES student(id), payment_date DATETIME);
CREATE TABLE park (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, student_id BIGINT FOREIGN KEY REFERENCES student(id), subject_id BIGINT FOREIGN KEY REFERENCES subject(id), mark INT);